### PR TITLE
Initial documentation build

### PR DESCRIPTION
**Pull request by ConnectedSystems**
Continuation of #243 

Website should deploy at https://open-aims.github.io/ADRIA.jl

### CODE REVIEW

**Comment by ConnectedSystems** [comment]
@Rosejoycrocker https://open-aims.github.io/ADRIA.jl/previews/PR244/

Fingers crossed I have it correctly set up now so docs for `main` build when you approve and merge.

**Comment by Rosejoycrocker** [comment]
Oh cool, looks great! So the documentation for functions and stuff can be automatically integrated with this also?

**Comment by ConnectedSystems** [comment]
That's its purpose, yes.

**Review by Rosejoycrocker — APPROVED** [review]

**Comment by Rosejoycrocker** [comment]
Do you have any more changes or can I merge?

**Comment by ConnectedSystems** [comment]
Go ahead and merge, I'll set up a docs branch to continue working there.

**Pull request merged**
