### PR TITLE
Reorganize package structure

### PR DESCRIPTION
**Pull request by ConnectedSystems**
Reorganize code and files in a more conceptually coherent structure.

### CODE REVIEW

**Comment by Rosejoycrocker** [comment]
Is it ok to review this now @ConnectedSystems ?

**Comment by ConnectedSystems** [comment]
This is marked as a draft, Rose.

Aside from that, no,  it needs to be updated to match recent changes on main

**Comment by Rosejoycrocker** [comment]
I know, It's just above you said to hold off until we have species changes in and we have them in now. But I'll leave it.

**Comment by ConnectedSystems** [comment]
Yes, I need to fix up the differences in those changes (see for example the list of files with conflicts).

**Comment by ConnectedSystems** [comment]
Ready for your review now @Rosejoycrocker

**Review by Rosejoycrocker — APPROVED** [review]
Looks good to me, scenarios also running fine and all tests passing.

**Pull request merged**
