### PR TITLE
Add tests for figure creation

### PR DESCRIPTION
**Pull request by ConnectedSystems**
As in title.

Requires #598 to be merged in first, followed by a rebase onto main.

### CODE REVIEW

**Comment by Zapiano** [comment]
This seems to be doing much more than just adding tests for figure creation 🤔

**Comment by ConnectedSystems** [comment]
You'll have to forgive the unrelated changes that mark struct fields as constant - I didn't want to submit a PR for three lines.

**Review by Zapiano — APPROVED** [review]
I really think we should put these two functions (and call them) in a separate file called `viz.jl` or something like that. Besides being more organized, it'll make it easier in the future if we want to run just this test apart from the rest. 

But other than that, lgtm

**Comment by ConnectedSystems** [comment]
I agree that would be cleaner. This was a quick implementation. Let's iterate towards that perfect solution.

**Pull request merged**
