### PR TITLE
Yax viz

### PR DESCRIPTION
**Pull request by DanTanAtAims**
Update the Viz module to use YAXArrays. 

Adds temporary type conversions to runtests.jl to allow for testing.

### CODE REVIEW

**Comment by ConnectedSystems** [comment]
Hi @DanTanAtAims

If you have evidence this works (e.g., figures or a script to produce figures), please share.

**Comment by DanTanAtAims** [comment]
Use the following [gist](https://gist.github.com/DanTanAtAims/d26e5f59ca3c90bb9f897447396bd973) to produce all the plots and test the migration.

I will add a much smaller task which is testing the viz.outcome_map! function once #702 merged.

**Review by Zapiano — APPROVED** [review]
Some minor comments but, overall, LGTM.

**Comment by Zapiano** [comment]
> Use the following [gist](https://gist.github.com/DanTanAtAims/d26e5f59ca3c90bb9f897447396bd973) to produce all the plots and test the migration.
> 
> I will add a much smaller task which is testing the viz.outcome_map! function once #702 merged.

I've run your gist code and the plots are all working fine. But next time, it would be easier if you can add all plots/figures (and other relevant evidence) to the PR to help the reviewer.

**Comment by ConnectedSystems** [comment]
There was a lot of conflicting changes from the massive merge that happened the other day.
I've cleaned up and aligned as best as I could.

**Pull request merged**
