### PR TITLE
v0.4.3 merge

### PR DESCRIPTION
**Pull request by ConnectedSystems**

### CODE REVIEW

**Comment by ConnectedSystems** [comment]
Hi @Rosejoycrocker could you please run tests on your end and approve if all pass?  (PRs cannot be merged into main without review)

I've run tests on my end and they pass but would like confirmation.

**Comment by Rosejoycrocker** [comment]
> Hi @Rosejoycrocker could you please run tests on your end and approve if all pass? (PRs cannot be merged into main without review)
> 
> I've run tests on my end and they pass but would like confirmation.

Sure, I'll run them now :)

**Comment by Rosejoycrocker** [comment]
Hey @ConnectedSystems, all tests passing on my end

**Comment by Rosejoycrocker** [comment]
I'll just quickly review code changes and then approve

**Comment by ConnectedSystems** [comment]
Most if not all changes should have been reviewed before as this is the v0.4.3 branch

**Comment by Rosejoycrocker** [comment]
Yeah realising I've seen most of this, I'll approve now

**Review by Rosejoycrocker — APPROVED** [review]

**Pull request merged**
