### PR TITLE
Deactivated interventions should be considered separately

### PR DESCRIPTION
**Pull request by ConnectedSystems**
If fog/SRM inteventions are not considered separately, post-processing will be incorrectly applied.

https://github.com/open-AIMS/ADRIA.jl/pull/582#discussion_r1393649977
https://github.com/open-AIMS/ADRIA.jl/pull/582#discussion_r1400087136

Rose, is the change in this PR appropriate?

### CODE REVIEW

**Comment by Rosejoycrocker** [comment]
I'll have a deeper look, but it may not be because we still use `shade_years` and `shade_start_year` to decide when to fog and when to apply SRM I think. I think it could work if we separate the timing parameters.

**Comment by ConnectedSystems** [comment]
> Or would we generally only be fogging when we shade?

I think they should be considered separately, applying SRM first.

**Comment by ConnectedSystems** [comment]
Okay, could you do that please?

**Comment by Rosejoycrocker** [comment]
> Okay, could you do that please?

Sure :)

**Review by ConnectedSystems — COMMENTED** [review]
@Zapiano 

Could you please approve this? No need for a review as the bulk of the changes were reviewed in #602.

Tests, plus figure creation, all pass and are confirmed to work.

**Comment by Zapiano** [comment]
@ConnectedSystems do you also want me to merge?

**Pull request merged**
