### PR TITLE
Changes to mcda factors following sensitivity analysis

### PR DESCRIPTION
**Pull request by Rosejoycrocker**
PR to discuss and apply changes to location selection criteria factors based on sensitivity analyses carried out on Moore and GBR Domains for ADRIA. Analysis for average absolute coral cover for the whole simulation time period, mid century and end of century. Based on 131072 runs for the Moore domain.

### CODE REVIEW

**Comment by Rosejoycrocker** [comment]
1. `guided` factor, over whole time period, Moore domain:
outcome_map_guided_moore_alltime
Peak sensitivity a methods 10-MAIRCA, 12-MOORA and 16, SAW method.
2. `guided` factor, over whole time period, synthetic domain:
outcome_map_guided_synth_alltime
Peak sensitivity at 3- Topsis, but lower sensitivity over all. Second smaller peak at 12-MOORA.
3. `guided` factor, over whole time period, ReefMod domain

**Comment by Rosejoycrocker** [comment]
1. `guided` factor for Moore domain, over "mid-century" (2035-2065 chosen as if deployments begin in 2025 this is probably the period where impacts will be seen)
outcome_map_guided_moore_3565
Peak sensitivity at 10-MAIRCA and 12-MOORA.
2. `guided` factor for synthetic domain for mid-century:
outcome_map_guided_synth_3565
Peak sensitivity for 9-MABAC, 6 - CODAS and 12 - MOORA.

**Comment by Rosejoycrocker** [comment]
1. `guided` factor for Moore domain for "end of century" (defined here as 2065-2099):
outcome_map_guided_moore_6599
Peak sensitivity at 10 - MAIRCA and 15/16 - ROV/SAW.
2. `guided` factor for synthetic domain for "end of century"
outcome_map_guided_synth_6599
Similar peaks to Moore for this time period.

**Comment by Rosejoycrocker** [comment]
1. Criteria weighting outcome mapping for seeding factors, Moore domain, whole of time period:
outcome_map_seed_crit_alltime
- wave-stress dips around 0.8
- heat stress peaks around 0.6
- Zone predecessor peaks around 0.6 and then dips at 0.7.
- Distance threshold peaks around 0.4.
- Out conn peaks from 0.4-0.8.
- low are tol dips at 0.6.
- risk tol peaks at 0.9
2. Criteria weighting outcome mapping for seeding factors, synthetic domain, whole of time period:
outcome_map_synth_seed_crit_alltime
-  wave stress dips at 0.6
- less variance for heat stress, probably due to less DHW variance.
- out conn peak at 0.5.
- risk tol peak between 0.85 and 0.9.
-  low coral cover dip at 0.8.
- low area tol dip at 0.6.
- dist tol grows in sensitivity if greater than 0.5.

**Comment by Rosejoycrocker** [comment]
1. Criteria weighting outcome mapping for shading factors, Moore domain, whole of time period:
outcome_map_shade_crit_alltime
 - wave stress dips at 0.8.
 - heat stress peaks at 0.6.
 - Zone predecessor peaks at 0.4.
 - shade conn dips at 0.5.
 
2.  Criteria weighting outcome mapping for shading factors, synthetic domain, whole of time period:
outcome_map_shade_crit_alltime_synth
- dip in wave stress at 0.8
- peak in heat stress at 0.6.
- peak in zone predecessor at 0.4.
- dip in shade conn at 0.5.

**Comment by Rosejoycrocker** [comment]
1. Criteria weighting outcome mapping for seeding factors, Moore domain, mid-century:
outcome_map_seed_crit_3565
- dip in wave stress at 0.7 but less noticeable.
- out conn peaks around 0.5.
- in conn dips at 0.7.
- dist thresh sensitvity varies.

**Comment by Rosejoycrocker** [comment]
1. Criteria weighting outcome mapping for shading factors, Moore domain, mid-century:
outcome_map_shade_crit_3565
- dip in wave stress around 0.7
- small peak in heat stress around 0.6.
- dip in shade conn around 0.5.
- small peak in zone predecessor at 0.4.
2. Criteria weighting outcome mapping for shading factors, synthetic domain, mid-century:
outcome_map_shade_crit_3565_synth
- dip in wave stress around 0.6.
- dip in shade conn around 0.5.
- peak in zone predecessor around 0.3-0.4.

**Comment by Rosejoycrocker** [comment]
1. Criteria weighting outcome mapping for seeding factors, Moore domain, end of century:
outcome_map_seed_crit_6599
- peak in wave stress around 0.9
- peak in heat stress 0.6-0.7.

1. Criteria weighting outcome mapping for seeding factors, synthetic domain, end of century:
outcome_map_seed_crit_6599_synth
- less variance in snsitivity for low are tol >0.6
- dist thresh increases after ~0.8.
- peak in wave stress around 0.6.
- peak in heat stress around 0.5.
- dip in low coral cover around 0.5.
- peak in incoming conn around 0.6.

**Comment by Rosejoycrocker** [comment]
1. Criteria weighting outcome mapping for shading factors, Moore domain, end of century:
outcome_map_shade_crit_6599
- peak in wave stress around 0.9.
- -small peak in heat stress around 0.6-0.7.
- peak in shade conn around 0.4.
- dip in high cover around 0.8.
- peak in zone predecessor around 0.4.

2.  Criteria weighting outcome mapping for shading factors, synthetic domain, end of century:
outcome_map_shade_crit_6599_synth
- peak in heat stress around 0.5.
- peak in zone predec around 0.3.
- peak in shade conn 0.5-0.7.
- peak in wave stress 0.5-0.7

**Comment by Rosejoycrocker** [comment]
Convergence: plot for guided parameter PAWN sensitivity against increasing N. (For Moore domain using average coral cover over all time) (more scenarios to follow)
outcome_maps_N_synth
Convergence: plot for seeding parameters PAWN sensitivity against increasing N. (For Moore domain using average coral cover over all time) (more scenarios to follow):
outcome_maps_foi_seed
Convergence: plot for shading parameters PAWN sensitivity against increasing N. (For Moore domain using average coral cover over all time) (more scenarios to follow):
outcome_maps_foi_shade

**Comment by Rosejoycrocker** [comment]
Some parameters seem to have coverged, e.g. dist thresh:
outcome_maps_foi_seed png_dist_thresh

Others still approaching convergence, e.g. heat stress:
outcome_maps_foi_seed png_heat_stress

(will update shortly with 8192 included in plot)

**Comment by Rosejoycrocker** [comment]
Convergence: plot for guided parameter PAWN sensitivity against increasing N. For Moore domain, line is the mean value, shading is 1 std. Again seems several factors have not converged. The stand out factor in the shading factors is `shade_start_year`.
outcome_maps_foi_guided_moore
outcome_maps_foi_seed_moore
outcome_maps_foi_shade_moore

**Comment by Rosejoycrocker** [comment]
1. Seeding factors, over whole time period, Moore domain:

outcome_map_seed_crit_alltime


2. Seeding factors, over mid-century, Moore domain:
outcome_map_seed_crit_3565



3. Seeding factors, over mid-century, Moore domain 

outcome_map_seed_crit_6599

**Comment by Rosejoycrocker** [comment]
1. Shading factors, over whole time period, Moore domain:

outcome_map_shade_crit_alltime



2. Shading factors, over mid-century, Moore domain:

outcome_map_shade_crit_3565


3. Shading factors, over end-of-century, Moore domain 

outcome_map_shade_crit_6599

**Comment by ConnectedSystems** [comment]
I'm closing this due to recent work superseding this set of analyses.

@Rosejoycrocker when ready, either rebase and reopen this PR or open a new one with a comment referring to this one.

**Pull request closed without merging**
