### PR TITLE
Deprecate `run_scenarios(scens, dom, ...)`

### PR DESCRIPTION
**Pull request by ConnectedSystems**
As in title.

Deprecate `run_scenarios(scens, dom, ...)` in favour of `run_scenarios(dom, scens, ...)` for consistency with other ADRIA methods.

For the most part I have not made changes to match with Blue. I think I'll do that as a larger effort.

### CODE REVIEW

**Comment by ConnectedSystems** [comment]
Part of #465

**Comment by Zapiano** [comment]
@ConnectedSystems do you prefer doing the same for the `run_scenario` in a separate PR?

**Comment by ConnectedSystems** [comment]
Ah, let me address that in this one!

**Comment by ConnectedSystems** [comment]
Ready for another review @Zapiano

**Review by Zapiano — APPROVED** [review]

**Pull request merged**
