### PR TITLE
Initial setup for documentation

### PR DESCRIPTION
**Pull request by ConnectedSystems**
Website should deploy at https://open-aims.github.io/ADRIA.jl

### CODE REVIEW

**Comment by ConnectedSystems** [comment]
PS: Once this is merged we would leave the `gh-pages` branch alone

**Comment by Rosejoycrocker** [comment]
Right, so if I add to the documentation I should do it on another branch?

**Comment by ConnectedSystems** [comment]
Yes, that's right.

Once your changes get merged into either a branch starting with `v` or into `main` the documentation build process will kick off as you can see here.

**Comment by ConnectedSystems** [comment]
Not yet - the build hasn't finished

**Comment by ConnectedSystems** [comment]
And still no because I misconfigured something - let me look into this more

**Comment by Rosejoycrocker** [comment]
all good, thanks

**Comment by ConnectedSystems** [comment]
Closing and retrying from a different branch.

**Pull request closed without merging**
