### PR TITLE
Scenario viz change

### PR DESCRIPTION
**Pull request by ConnectedSystems**
Place density plot with histogram.

image

Things left to do: 

- [x] Update documentation
- [x] Allow user to hide legend (looks nicer when composing multiple plots together)

### CODE REVIEW

**Comment by ConnectedSystems** [comment]
@Rosejoycrocker ready for review. Note I've updated example usage in the documentation, but not the corresponding figure. I intend to update all figures over the next few weeks.

**Comment by Zapiano** [comment]
@ConnectedSystems have you considered using a Kernel Density plot instead of histogram? It can be easier to visualize when you only need the shape and there's intersection.

**Comment by ConnectedSystems** [comment]
@Zapiano yes, that's essentially what we're moving away from.

Reason is the density plot can be interpreted in a misleading way (in my view).
Perhaps this will change after the MCDA assessments @Rosejoycrocker is doing currently.

image

**Review by Rosejoycrocker — APPROVED** [review]
Looks good to me

**Pull request merged**
