### PR TITLE
restructured documentation image directories

### LINKED ISSUE #567: Reorganize files/images for documentation
Image files for the documentation are placed in one folder with no organization (everything in the one folder). Better to reorganize these into sub-directories for each page where relevant.

> I dislike having `example` / `ex` / `eg` in the filename. A better organisation approach would be to have images in separate directories for each page.
> e.g., `assets/imgs/analysis/selected_locations_map.png`
> I will raise a separate issue for this to be tackled.

_Originally posted by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/449#discussion_r1384217217_

### PR DESCRIPTION
**Pull request by DanTanAtAims**
In the issue it mentions updating the filename within the documentation here

```julia
save("ranks_plot_ex.png", tf)  # this filename has to be updated
```
was the idea to change it to the following

```julia
save("analysis/ranks_plot_ex.png", tf)
```
closes #567

### CODE REVIEW

**Comment by ConnectedSystems** [comment]
I think it's okay to _not_ refer to the directory when saving plots, but *remove* any reference to "example": such as `ex`, `eg`, etc. 

The idea is the user should be able to run the examples directly with as little setup as possible (e.g., creating directories).

**Comment by DanTanAtAims** [comment]
It looks like rose standardised the filenames in the original pull request (#449) as all example suffixes have been removed. 

If you are happy with the new file structure this should be ready for merge.

**Comment by ConnectedSystems** [comment]
Awesome, thanks

**Review by ConnectedSystems — APPROVED** [review]
All is well!

**Pull request merged**
